"""create all tables

Revision ID: 05565b9d1399
Revises: 33c5e3214331
Create Date: 2025-10-05 13:22:13.777631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05565b9d1399'
down_revision: Union[str, Sequence[str], None] = '33c5e3214331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('doc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'doc')
    # ### end Alembic commands ###
