"""create all tables

Revision ID: 33c5e3214331
Revises: ccf3cbb23590
Create Date: 2025-10-05 13:21:36.885926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c5e3214331'
down_revision: Union[str, Sequence[str], None] = 'ccf3cbb23590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'doc')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('doc', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
