"""create all tables

Revision ID: 3c5bcc795d31
Revises: 266754ca904f
Create Date: 2025-10-21 11:06:40.583669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5bcc795d31'
down_revision: Union[str, Sequence[str], None] = '266754ca904f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
