"""create all tables

Revision ID: 6a6679208400
Revises: f239669dcfda
Create Date: 2025-10-07 12:03:49.716757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6679208400'
down_revision: Union[str, Sequence[str], None] = 'f239669dcfda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('departure_time', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'departure_time')
    # ### end Alembic commands ###
