"""create all tables

Revision ID: 8ad70dfa55d0
Revises: 87cafb35bd91
Create Date: 2025-10-05 13:26:55.956744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad70dfa55d0'
down_revision: Union[str, Sequence[str], None] = '87cafb35bd91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_u_id'), table_name='u')
    op.drop_table('u')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('u',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('u_pkey'))
    )
    op.create_index(op.f('ix_u_id'), 'u', ['id'], unique=False)
    # ### end Alembic commands ###
