"""create all tables

Revision ID: af9735f4442a
Revises: 444f779596be
Create Date: 2025-10-07 11:42:16.468159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af9735f4442a'
down_revision: Union[str, Sequence[str], None] = '444f779596be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('departuret', sa.Text(), nullable=False))
    op.add_column('posts', sa.Column('destination', sa.Text(), nullable=False))
    op.add_column('posts', sa.Column('details', sa.Text(), nullable=False))
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'details')
    op.drop_column('posts', 'destination')
    op.drop_column('posts', 'departuret')
    # ### end Alembic commands ###
