"""create all tables

Revision ID: b96964593c7f
Revises: af9735f4442a
Create Date: 2025-10-07 11:43:09.643435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96964593c7f'
down_revision: Union[str, Sequence[str], None] = 'af9735f4442a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('departure', sa.Text(), nullable=False))
    op.drop_column('posts', 'departuret')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('departuret', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'departure')
    # ### end Alembic commands ###
